[tox]
envlist = py311, py312, py313
isolated_build = True

[tox:.package]
basepython = python3

[testenv]
deps = pytest
commands =
    pytest
passenv = EUROPEANA_API_KEY

[flake8]
max-line-length=120
