name: Publish on PyPi

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Path
      run: |
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

    - name: Install Base Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv pipx
        pipx install poetry

    - name: Install Python Dependencies
      run: |
        poetry install

    - name: Publish
      run: |
        poetry build
        poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
